baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lumberj3ck website'
dateFmt = '15:04:05 2006-01-02'
pygmentsUseClasses = true
pygmentsCodefences = true
goldmark.renderer.unsafe = true 
[params]
  description = "Explore my insightful blog  Discover the latest articles, tips, and tutorials to help you achieve your goals." 
  author = 'Lumberj3ck'
